version: '3.8'
services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: usersdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  web:
    build: ./app
    restart: always
    environment:
      DB_HOST: db
      DB_NAME: usersdb
      DB_USER: user
      DB_PASSWORD: password
    ports:
      - "80:5000"
    depends_on:
      - db
volumes:
  db-data:
